// <auto-generated />
using System;
using CMRmvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMRmvc.Migrations
{
    [DbContext(typeof(CRMContext))]
    [Migration("20200925122838_Role.in.User")]
    partial class RoleinUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMRmvc.Models.MenuHijoAcciones", b =>
                {
                    b.Property<long>("IdMenuHijoAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdMenuHijo")
                        .HasColumnType("bigint");

                    b.Property<string>("MhaClase")
                        .HasColumnName("mhaClase")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MhaIcono")
                        .HasColumnName("mhaIcono")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MhaKey")
                        .HasColumnName("mhaKey")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool?>("MhaNewTab")
                        .HasColumnName("mhaNewTab")
                        .HasColumnType("bit");

                    b.Property<int?>("MhaOrden")
                        .HasColumnName("mhaOrden")
                        .HasColumnType("int");

                    b.Property<string>("MhaTexto")
                        .HasColumnName("mhaTexto")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("MhaTooltip")
                        .HasColumnName("mhaTooltip")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MhaUrl")
                        .HasColumnName("mhaURL")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("IdMenuHijoAccion")
                        .HasName("PK__MenuHijo__CB9BC911C217FB02");

                    b.HasIndex("IdMenuHijo");

                    b.ToTable("MenuHijoAcciones");
                });

            modelBuilder.Entity("CMRmvc.Models.MenuItemHijo", b =>
                {
                    b.Property<long>("IdMenuHijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controlador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("IdMenuPadre")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMenuHijo")
                        .HasName("PK__MenuItem__E5A0389D88729454");

                    b.HasIndex("IdMenuPadre");

                    b.ToTable("MenuItemHijo");
                });

            modelBuilder.Entity("CMRmvc.Models.MenuItemPadre", b =>
                {
                    b.Property<long>("IdMenuPadre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdMenuPadre")
                        .HasName("PK__MenuItem__2C1D57B55FAE039B");

                    b.ToTable("MenuItemPadre");
                });

            modelBuilder.Entity("CMRmvc.Models.Parametros", b =>
                {
                    b.Property<long>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idParametro")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("FecDel")
                        .HasColumnName("FecDEL")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FecIns")
                        .HasColumnName("FecINS")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FecUpd")
                        .HasColumnName("FecUPD")
                        .HasColumnType("datetime");

                    b.Property<long>("IdParametroTipo")
                        .HasColumnName("idParametroTipo")
                        .HasColumnType("bigint");

                    b.Property<short>("ParAdmin")
                        .HasColumnName("parAdmin")
                        .HasColumnType("smallint");

                    b.Property<string>("ParClave")
                        .IsRequired()
                        .HasColumnName("parClave")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ParNombre")
                        .IsRequired()
                        .HasColumnName("parNombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<short>("ParTipo")
                        .HasColumnName("parTipo")
                        .HasColumnType("smallint");

                    b.Property<string>("ParValor")
                        .IsRequired()
                        .HasColumnName("parValor")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("UsrDel")
                        .HasColumnName("UsrDEL")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsrIns")
                        .HasColumnName("UsrINS")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsrUpd")
                        .HasColumnName("UsrUPD")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("IdParametro")
                        .HasName("PK__Parametr__9C816E5F89DA85D0");

                    b.HasIndex("IdParametroTipo");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("CMRmvc.Models.ParametrosTipo", b =>
                {
                    b.Property<long>("IdParametroTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idParametroTipo")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("TipAdmin")
                        .HasColumnName("tipAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("TipDescripcion")
                        .HasColumnName("tipDescripcion")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("TipNombre")
                        .IsRequired()
                        .HasColumnName("tipNombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool?>("TipVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tipVisible")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("IdParametroTipo")
                        .HasName("PK__Parametr__A8D83328843AB2AC");

                    b.ToTable("ParametrosTipo");
                });

            modelBuilder.Entity("CMRmvc.Models.PerfilMenuHijo", b =>
                {
                    b.Property<long>("IdPerfilMenuHijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdMenuHijo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint");

                    b.HasKey("IdPerfilMenuHijo")
                        .HasName("PK__PerfilMe__9043AF82B0D81B66");

                    b.HasIndex("IdMenuHijo");

                    b.ToTable("PerfilMenuHijo");
                });

            modelBuilder.Entity("CMRmvc.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("CMRmvc.Models.RolesAcciones", b =>
                {
                    b.Property<long>("IdPerfilAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdMenuHijoAccion")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint");

                    b.HasKey("IdPerfilAccion")
                        .HasName("PK__RolesAcc__56ADAC70D8C3C5BA");

                    b.HasIndex("IdMenuHijoAccion");

                    b.ToTable("RolesAcciones");
                });

            modelBuilder.Entity("CMRmvc.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FecClaveVcto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecDel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecIns")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecUltIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecUpd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("NroLoginNok")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("UsrDel")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UsrIns")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UsrUpd")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CMRmvc.Models.MenuHijoAcciones", b =>
                {
                    b.HasOne("CMRmvc.Models.MenuItemHijo", "IdMenuHijoNavigation")
                        .WithMany("MenuHijoAcciones")
                        .HasForeignKey("IdMenuHijo")
                        .HasConstraintName("MenuAcciones_MenuHijo_FK")
                        .IsRequired();
                });

            modelBuilder.Entity("CMRmvc.Models.MenuItemHijo", b =>
                {
                    b.HasOne("CMRmvc.Models.MenuItemPadre", "IdMenuPadreNavigation")
                        .WithMany("MenuItemHijo")
                        .HasForeignKey("IdMenuPadre")
                        .HasConstraintName("MenuPadre_MenuHijo_FK")
                        .IsRequired();
                });

            modelBuilder.Entity("CMRmvc.Models.Parametros", b =>
                {
                    b.HasOne("CMRmvc.Models.ParametrosTipo", "IdParametroTipoNavigation")
                        .WithMany("Parametros")
                        .HasForeignKey("IdParametroTipo")
                        .HasConstraintName("Parametros_ParametroTipo_FK")
                        .IsRequired();
                });

            modelBuilder.Entity("CMRmvc.Models.PerfilMenuHijo", b =>
                {
                    b.HasOne("CMRmvc.Models.MenuItemHijo", "IdMenuHijoNavigation")
                        .WithMany("PerfilMenuHijo")
                        .HasForeignKey("IdMenuHijo")
                        .HasConstraintName("MenuItemHijo_PerfilMenuHijo_FK")
                        .IsRequired();
                });

            modelBuilder.Entity("CMRmvc.Models.RolesAcciones", b =>
                {
                    b.HasOne("CMRmvc.Models.MenuHijoAcciones", "IdMenuHijoAccionNavigation")
                        .WithMany("RolesAcciones")
                        .HasForeignKey("IdMenuHijoAccion")
                        .HasConstraintName("MenuAcciones_RolesAcciones_FK")
                        .IsRequired();
                });

            modelBuilder.Entity("CMRmvc.Models.User", b =>
                {
                    b.HasOne("CMRmvc.Models.Role", "RoleIDNavigation")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("CMRmvc.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("CMRmvc.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("CMRmvc.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("CMRmvc.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMRmvc.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("CMRmvc.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
